// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAIOYzjD6TqNxgDGObRvuojyXlxw5sjak',
    appId: '1:640790442411:web:621e6dd8baa48216d522ee',
    messagingSenderId: '640790442411',
    projectId: 'erdem-5e13c',
    authDomain: 'erdem-5e13c.firebaseapp.com',
    storageBucket: 'erdem-5e13c.firebasestorage.app',
    measurementId: 'G-8YZ6S9KJ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_j1UJ8hhquMm-VNjWsgwbO5CcLCyrZww',
    appId: '1:640790442411:android:5b43449119e8631bd522ee',
    messagingSenderId: '640790442411',
    projectId: 'erdem-5e13c',
    storageBucket: 'erdem-5e13c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYj_lIud2KyNkem0Eg-dKiGF01wSkg_o',
    appId: '1:640790442411:ios:38bd8092ddb06db9d522ee',
    messagingSenderId: '640790442411',
    projectId: 'erdem-5e13c',
    storageBucket: 'erdem-5e13c.firebasestorage.app',
    iosBundleId: 'com.erdemakdag.flutterFirebaseDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYj_lIud2KyNkem0Eg-dKiGF01wSkg_o',
    appId: '1:640790442411:ios:38bd8092ddb06db9d522ee',
    messagingSenderId: '640790442411',
    projectId: 'erdem-5e13c',
    storageBucket: 'erdem-5e13c.firebasestorage.app',
    iosBundleId: 'com.erdemakdag.flutterFirebaseDersleri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAIOYzjD6TqNxgDGObRvuojyXlxw5sjak',
    appId: '1:640790442411:web:2981c8884c33dcecd522ee',
    messagingSenderId: '640790442411',
    projectId: 'erdem-5e13c',
    authDomain: 'erdem-5e13c.firebaseapp.com',
    storageBucket: 'erdem-5e13c.firebasestorage.app',
    measurementId: 'G-RFS9CLN69V',
  );
}
